#一种数据序列化格式：易阅读，重数据轻格式，易与脚本语言交互
#    大小写敏感
#    属性层级使用多行描述，每行结尾使用冒号结束
#    用缩进表示层级关系，同层级左侧对齐，只允许使用空格（不允许tab）
#    属性值前面添加空格（冒号+空格分隔）
     #表示注释

#数组格式
##likes:
##  - music
##  - game
##  - PE
lesson: SpringBoot

#server:
#  port: 80

enterprise:
  name: itcast
  age: 16
  tel: 4006184000
  subject:
    - Java
    - 前端
    - 大数据
